services:
  mf-automation:
    build: .
    restart: on-failure
    env_file:
      - .env
    environment:
      MONEYFORWARD_COOKIES: /data/moneyforward.cookies.txt
    volumes:
      - ./cookies/moneyforward.cookies.txt:/data/moneyforward.cookies.txt:ro
